### ISSUE TITLE
Theme or plugin CSS could interfere with Foyer's styling

### ISSUE THREAD

**Issue by mennolui** [mennolui/wp-foyer#23]
Most notably the `body`, `figure`, `img`, `iframe` and `video` elements.

**Comment by mennolui** [comment]
Add some resets to the Foyer CSS?

**Comment by mennolui** [comment]
Workarounds used so far:

Themes adding a scrollbar, visible on Edge even when no scrolling needed:

```CSS
html {
  overflow-y: auto !important;
}
```

Themes adding bars above/below every page:

```CSS
body.single-foyer_display, body.single-foyer_channel, body.single-foyer_slide {
    padding: 0 !important;
}
```
